In [10]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [11]:
import numpy as np
import pandas as pd

In [12]:
from tensorflow import keras

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Bidirectional



In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('preprocessed_clean_train_set.csv')

In [16]:
df.head()

keyword location                                               text  target  \
0     NaN      NaN  Our Deeds are the Reason of this #earthquake M...       1   
1     NaN      NaN             Forest fire near La Ronge Sask. Canada       1   
2     NaN      NaN  All residents asked to 'shelter in place' are ...       1   
3     NaN      NaN  13,000 people receive #wildfires evacuation or...       1   
4     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...       1   

   total_words  char_count  sentence_count  avg_word_length  \
0           13          57               1         4.384615   
1            7          32               2         4.571429   
2           22         112               2         5.090909   
3            9          57               1         6.333333   
4           17          72               1         4.235294   

   avg_sentence_lenght                                     tokenized_text  \
0                 13.0  ['Our', 'Deeds', 'are', 'the', 'Reason', 'of',...   
1                  3.5  ['Forest', 'fire', 'near', 'La', 'Ronge', 'Sas...   
2                 11.0  ['All', 'residents', 'asked', 'to', "'", 'shel...   
3                  9.0  ['13,000', 'people', 'receive', '#wildfires', ...   
4                 17.0  ['Just', 'got', 'sent', 'this', 'photo', 'from...   

                                          clean_text  clean_total_words  \
0                               reason allah forgive                  3   
1                   forest fire near la range canada                  6   
2  resident ask shelter place officer evacuation ...                 10   
3                 people evacuation order california                  4   
4                        get send photo smoke school                  5   

   clean_char_count  clean_sentence_count  clean_avg_word_length  \
0                18                     1                   6.00   
1                27                     1                   4.50   
2                63                     1                   6.30   
3                31                     1                   7.75   
4                23                     1                   4.60   

   clean_avg_sentence_lenght  
0                        3.0  
1                        6.0  
2                       10.0  
3                        4.0  
4                        5.0

In [17]:
df = df.dropna(subset=['clean_text'])
X = df['clean_text']
y = df['target']

X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=.2, random_state=40521)

In [18]:
tokenizer = Tokenizer(num_words = 1000, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)
word_index = tokenizer.word_index

In [19]:
sequences = tokenizer.texts_to_sequences(X_train)
padded = pad_sequences(sequences, padding="post", truncating='post')

In [20]:
sequences

[[19, 389],
 [1, 1, 741, 180],
 [365, 90, 504, 43, 151, 158, 11, 430, 109, 545, 135],
 [72],
 [50, 478, 1, 1, 1, 916, 1],
 [312, 70, 201, 9, 649, 1, 917, 30, 312, 70, 201, 9],
 [390, 63, 55, 190, 313, 842, 918, 390, 190],
 [53],
 [505, 15, 684, 575, 521, 75, 366, 450, 685, 686],
 [1, 479, 55, 221],
 [687, 19, 19, 51, 86],
 [789, 742],
 [33, 1, 480, 367, 688],
 [451, 201, 314, 3, 431, 128, 38],
 [110, 576, 1, 1, 250],
 [202, 506, 843, 315, 316],
 [76, 743],
 [235, 577, 1, 1, 191, 844, 235, 30],
 [278, 1],
 [11],
 [222, 140, 790, 3, 171, 578, 2, 3, 171, 129, 919],
 [90, 504, 43, 151, 158, 11, 430, 109, 545, 135],
 [744, 368, 650, 505, 651],
 [652, 522, 432, 615, 546, 1],
 [653, 1, 1, 265, 32, 340],
 [1, 689, 317, 294],
 [481, 654, 1, 181, 34, 1],
 [77, 745, 920],
 [122],
 [152, 655, 845, 655],
 [690, 1, 921, 1, 1, 1, 746, 16, 90, 1, 1, 921, 1],
 [91, 28, 295, 128, 38, 111],
 [192, 160, 78, 251, 172, 656, 41, 479, 27, 1, 656],
 [479, 507, 747, 1, 1, 747],
 [1, 53, 67, 846],
 [1, 296, 212,

In [21]:
word_index

{'<OOV>': 1,
 'like': 2,
 'fire': 3,
 'new': 4,
 'get': 5,
 'go': 6,
 'people': 7,
 'video': 8,
 'kill': 9,
 'crash': 10,
 'bomb': 11,
 'come': 12,
 'body': 13,
 'time': 14,
 'attack': 15,
 'year': 16,
 'emergency': 17,
 'man': 18,
 'want': 19,
 'burn': 20,
 'day': 21,
 'disaster': 22,
 'news': 23,
 'pm': 24,
 'know': 25,
 'family': 26,
 'look': 27,
 'home': 28,
 'storm': 29,
 'police': 30,
 'love': 31,
 'good': 32,
 'watch': 33,
 'work': 34,
 'flood': 35,
 'car': 36,
 'think': 37,
 'california': 38,
 'bag': 39,
 'building': 40,
 'scream': 41,
 'say': 42,
 'suicide': 43,
 'death': 44,
 'collapse': 45,
 'today': 46,
 'feel': 47,
 'let': 48,
 'life': 49,
 'train': 50,
 'world': 51,
 'wreck': 52,
 'need': 53,
 'low': 54,
 'drown': 55,
 'dead': 56,
 'help': 57,
 'destroy': 58,
 'way': 59,
 'nuclear': 60,
 'live': 61,
 'injury': 62,
 'fear': 63,
 'plan': 64,
 'war': 65,
 'blow': 66,
 'rescue': 67,
 'fall': 68,
 'find': 69,
 'wound': 70,
 'read': 71,
 'right': 72,
 'survive': 73,
 'accident'

In [22]:
padded

array([[ 19, 389,   0, ...,   0,   0,   0],
       [  1,   1, 741, ...,   0,   0,   0],
       [365,  90, 504, ...,   0,   0,   0],
       ...,
       [  1, 233,  57, ...,   0,   0,   0],
       [277,  61,   1, ...,   0,   0,   0],
       [ 43, 764,  73, ...,   0,   0,   0]])

In [23]:
padded[0]

array([ 19, 389,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [30]:
total_words = len(tokenizer.word_index)+1
max_sequence_len = max([len(x) for x in sequences])

In [31]:
model = Sequential()
model.add(Embedding(total_words,128, input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [32]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [33]:
y_train[:]

5487    0
185     0
7478    1
816     0
2439    1
       ..
3530    1
51      0
3433    1
4443    1
6432    0
Name: target, Length: 5968, dtype: int64

In [34]:
xs = padded[:,:-1]

In [35]:
history = model.fit(xs,y_train,epochs=10,verbose=1)

Epoch 1/10
187/187 [==============================] - 5s 10ms/step - loss: 0.5440 - accuracy: 0.7203
Epoch 2/10
187/187 [==============================] - 2s 10ms/step - loss: 0.4140 - accuracy: 0.8189
Epoch 3/10
187/187 [==============================] - 2s 10ms/step - loss: 0.3824 - accuracy: 0.8316
Epoch 4/10
187/187 [==============================] - 2s 10ms/step - loss: 0.3574 - accuracy: 0.8412
Epoch 5/10
187/187 [==============================] - 2s 9ms/step - loss: 0.3267 - accuracy: 0.8544
Epoch 6/10
187/187 [==============================] - 2s 10ms/step - loss: 0.3023 - accuracy: 0.8681
Epoch 7/10
187/187 [==============================] - 2s 10ms/step - loss: 0.2770 - accuracy: 0.8755
Epoch 8/10
187/187 [==============================] - 2s 10ms/step - loss: 0.2487 - accuracy: 0.8929
Epoch 9/10
187/187 [==============================] - 2s 9ms/step - loss: 0.2264 - accuracy: 0.8991
Epoch 10/10
187/187 [==============================] - 2s 10ms/step - loss: 0.2050 - accuracy

In [36]:
xs

array([[ 19, 389,   0, ...,   0,   0,   0],
       [  1,   1, 741, ...,   0,   0,   0],
       [365,  90, 504, ...,   0,   0,   0],
       ...,
       [  1, 233,  57, ...,   0,   0,   0],
       [277,  61,   1, ...,   0,   0,   0],
       [ 43, 764,  73, ...,   0,   0,   0]])

In [37]:
max_sequence_len

17

In [24]:
xs[0][0]

NameError: name 'xs' is not defined

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
X2 = df['clean_text']
y2 = df['target']

X_train2,X_test2,y_train2, y_test2 = train_test_split(X2,y2,test_size=.2, random_state=40521)

In [40]:
tfdf = TfidfVectorizer(min_df = 10,max_df = .5, ngram_range=(1,2))
tf_vect = tfdf.fit_transform(X_train2)

In [41]:
X_train_r = pd.DataFrame(tfdf.transform(X_train2).todense(),columns=tfdf.get_feature_names())
X_test_r = pd.DataFrame(tfdf.transform(X_test2).todense(),columns=tfdf.get_feature_names())
y_train_r = y_train2.copy()
y_test_r = y_test2.copy()

C:\Users\Nel-Jiren\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
C:\Users\Nel-Jiren\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [47]:
model2 = Sequential()
model2.add(Dense(32,activation='relu'))
model2.add(Dense(16,activation='relu'))
model2.add(Dense(1,activation='sigmoid'))

model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [48]:
history2 = model2.fit(X_train_r,y_train_r,epochs=32, validation_data=[X_test_r,y_test_r])

Epoch 1/32
187/187 [==============================] - 1s 6ms/step - loss: 0.6116 - accuracy: 0.6835 - val_loss: 0.4903 - val_accuracy: 0.7815
Epoch 2/32
187/187 [==============================] - 1s 5ms/step - loss: 0.4312 - accuracy: 0.8086 - val_loss: 0.4856 - val_accuracy: 0.7688
Epoch 3/32
187/187 [==============================] - 1s 5ms/step - loss: 0.3846 - accuracy: 0.8303 - val_loss: 0.4855 - val_accuracy: 0.7768
Epoch 4/32
187/187 [==============================] - 1s 4ms/step - loss: 0.3568 - accuracy: 0.8442 - val_loss: 0.5006 - val_accuracy: 0.7741
Epoch 5/32
187/187 [==============================] - 1s 5ms/step - loss: 0.3338 - accuracy: 0.8539 - val_loss: 0.5178 - val_accuracy: 0.7755
Epoch 6/32
187/187 [==============================] - 1s 4ms/step - loss: 0.3108 - accuracy: 0.8695 - val_loss: 0.5345 - val_accuracy: 0.7714
Epoch 7/32
187/187 [==============================] - 1s 4ms/step - loss: 0.2894 - accuracy: 0.8815 - val_loss: 0.5599 - val_accuracy: 0.7721
Epoch 

In [44]:
y_train_r

5487    0
185     0
7478    1
816     0
2439    1
       ..
3530    1
51      0
3433    1
4443    1
6432    0
Name: target, Length: 5968, dtype: int64

In [45]:
X_train_r

aba  aba woman  abandon  ablaze  absolutely  acc  acc news  accident  \
0     0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
1     0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
2     0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
3     0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
4     0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
...   ...        ...      ...     ...         ...  ...       ...       ...   
5963  0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
5964  0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
5965  0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
5966  0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   
5967  0.0        0.0      0.0     0.0         0.0  0.0       0.0       0.0   

      account  act  ...  year ago  year atomic  year old  yes  york  young  \
0         0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
1         0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
2         0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
3         0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
4         0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
...       ...  ...  ...       ...          ...       ...  ...   ...    ...   
5963      0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
5964      0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
5965      0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
5966      0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   
5967      0.0  0.0  ...       0.0          0.0       0.0  0.0   0.0    0.0   

      yous  youth  youtube  zone  
0      0.0    0.0      0.0   0.0  
1      0.0    0.0      0.0   0.0  
2      0.0    0.0      0.0   0.0  
3      0.0    0.0      0.0   0.0  
4      0.0    0.0      0.0   0.0  
...    ...    ...      ...   ...  
5963   0.0    0.0      0.0   0.0  
5964   0.0    0.0      0.0   0.0  
5965   0.0    0.0      0.0   0.0  
5966   0.0    0.0      0.0   0.0  
5967   0.0    0.0      0.0   0.0  

[5968 rows x 1208 columns]