In [4]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [5]:
import numpy as np
import pandas as pd

In [50]:
from tensorflow import keras

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Bidirectional

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [12]:
df = pd.read_csv('preprocessed_clean_train_set.csv')

In [13]:
df.head()

keyword location                                               text  target  \
0     NaN      NaN  Our Deeds are the Reason of this #earthquake M...       1   
1     NaN      NaN             Forest fire near La Ronge Sask. Canada       1   
2     NaN      NaN  All residents asked to 'shelter in place' are ...       1   
3     NaN      NaN  13,000 people receive #wildfires evacuation or...       1   
4     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...       1   

   total_words  char_count  sentence_count  avg_word_length  \
0           13          57               1         4.384615   
1            7          32               2         4.571429   
2           22         112               2         5.090909   
3            9          57               1         6.333333   
4           17          72               1         4.235294   

   avg_sentence_lenght                                     tokenized_text  \
0                 13.0  ['Our', 'Deeds', 'are', 'the', 'Reason', 'of',...   
1                  3.5  ['Forest', 'fire', 'near', 'La', 'Ronge', 'Sas...   
2                 11.0  ['All', 'residents', 'asked', 'to', "'", 'shel...   
3                  9.0  ['13,000', 'people', 'receive', '#wildfires', ...   
4                 17.0  ['Just', 'got', 'sent', 'this', 'photo', 'from...   

                                          clean_text  clean_total_words  \
0                               reason allah forgive                  3   
1                   forest fire near la range canada                  6   
2  resident ask shelter place officer evacuation ...                 10   
3                 people evacuation order california                  4   
4                        get send photo smoke school                  5   

   clean_char_count  clean_sentence_count  clean_avg_word_length  \
0                18                     1                   6.00   
1                27                     1                   4.50   
2                63                     1                   6.30   
3                31                     1                   7.75   
4                23                     1                   4.60   

   clean_avg_sentence_lenght  
0                        3.0  
1                        6.0  
2                       10.0  
3                        4.0  
4                        5.0

In [32]:
df = df.dropna(subset=['clean_text'])
X = df['clean_text']
y = df['target']

X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=.2, random_state=40521)

In [39]:
tokenizer = Tokenizer(num_words = 256, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)
word_index = tokenizer.word_index

In [45]:
sequences = tokenizer.texts_to_sequences(X_train)
padded = pad_sequences(sequences, padding="post", truncating='post')

In [46]:
sequences

[[19, 1],
 [1, 1, 1, 180],
 [1, 90, 1, 43, 151, 158, 11, 1, 109, 1, 135],
 [72],
 [50, 1, 1, 1, 1, 1, 1],
 [1, 70, 201, 9, 1, 1, 1, 30, 1, 70, 201, 9],
 [1, 63, 55, 190, 1, 1, 1, 1, 190],
 [53],
 [1, 15, 1, 1, 1, 75, 1, 1, 1, 1],
 [1, 1, 55, 221],
 [1, 19, 19, 51, 86],
 [1, 1],
 [33, 1, 1, 1, 1],
 [1, 201, 1, 3, 1, 128, 38],
 [110, 1, 1, 1, 250],
 [202, 1, 1, 1, 1],
 [76, 1],
 [235, 1, 1, 1, 191, 1, 235, 30],
 [1, 1],
 [11],
 [222, 140, 1, 3, 171, 1, 2, 3, 171, 129, 1],
 [90, 1, 43, 151, 158, 11, 1, 109, 1, 135],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 32, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 181, 34, 1],
 [77, 1, 1],
 [122],
 [152, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 16, 90, 1, 1, 1, 1],
 [91, 28, 1, 128, 38, 111],
 [192, 160, 78, 251, 172, 1, 41, 1, 27, 1, 1],
 [1, 1, 1, 1, 1, 1],
 [1, 53, 67, 1],
 [1, 1, 212, 46, 166],
 [166, 1, 115, 1, 35, 1, 1, 1, 1, 1, 7, 37, 36, 1],
 [60, 1, 203, 1, 252, 1, 1, 1, 203, 1],
 [1, 116, 1, 1, 1, 10, 16, 167, 1, 242, 1, 1, 1],
 [47, 1, 72],
 [1, 18

In [47]:
word_index

{'<OOV>': 1,
 'like': 2,
 'fire': 3,
 'new': 4,
 'get': 5,
 'go': 6,
 'people': 7,
 'video': 8,
 'kill': 9,
 'crash': 10,
 'bomb': 11,
 'come': 12,
 'body': 13,
 'time': 14,
 'attack': 15,
 'year': 16,
 'emergency': 17,
 'man': 18,
 'want': 19,
 'burn': 20,
 'day': 21,
 'disaster': 22,
 'news': 23,
 'pm': 24,
 'know': 25,
 'family': 26,
 'look': 27,
 'home': 28,
 'storm': 29,
 'police': 30,
 'love': 31,
 'good': 32,
 'watch': 33,
 'work': 34,
 'flood': 35,
 'car': 36,
 'think': 37,
 'california': 38,
 'bag': 39,
 'building': 40,
 'scream': 41,
 'say': 42,
 'suicide': 43,
 'death': 44,
 'collapse': 45,
 'today': 46,
 'feel': 47,
 'let': 48,
 'life': 49,
 'train': 50,
 'world': 51,
 'wreck': 52,
 'need': 53,
 'low': 54,
 'drown': 55,
 'dead': 56,
 'help': 57,
 'destroy': 58,
 'way': 59,
 'nuclear': 60,
 'live': 61,
 'injury': 62,
 'fear': 63,
 'plan': 64,
 'war': 65,
 'blow': 66,
 'rescue': 67,
 'fall': 68,
 'find': 69,
 'wound': 70,
 'read': 71,
 'right': 72,
 'survive': 73,
 'accident'

In [48]:
padded

array([[ 19,   1,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   0,   0,   0],
       [  1,  90,   1, ...,   0,   0,   0],
       ...,
       [  1, 233,  57, ...,   0,   0,   0],
       [  1,  61,   1, ...,   0,   0,   0],
       [ 43,   1,  73, ...,   0,   0,   0]])

In [49]:
padded[0]

array([19,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [58]:
total_words = len(tokenizer.word_index)+1
max_sequence_len = max([len(x) for x in sequences])

In [67]:
model = Sequential()
model.add(Embedding(total_words,64, input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [68]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [69]:
y_train[:]

5487    0
185     0
7478    1
816     0
2439    1
       ..
3530    1
51      0
3433    1
4443    1
6432    0
Name: target, Length: 5968, dtype: int64

In [70]:
xs = padded[:,:-1]

In [71]:
history = model.fit(xs,y_train,epochs=32,verbose=1)

Epoch 1/32
187/187 [==============================] - 4s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5729
Epoch 2/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 3/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 4/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 5/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 6/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 7/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 8/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 9/32
187/187 [==============================] - 2s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5719
Epoch 10/32
187/187 [==============================] - 

In [72]:
xs

array([[ 19,   1,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   0,   0,   0],
       [  1,  90,   1, ...,   0,   0,   0],
       ...,
       [  1, 233,  57, ...,   0,   0,   0],
       [  1,  61,   1, ...,   0,   0,   0],
       [ 43,   1,  73, ...,   0,   0,   0]])

In [73]:
max_sequence_len

17